#!/usr/bin/env python
# coding: utf-8


import os

#copy and paste this file in the folder where the files generated by the C code are 
# for instance for the test_graph, copy the file where the files test_graph.txt_query_subgraph_0_1.txt, etc. are
# then just run it, it will generate a new folder and insert the correct file with the new format in the folder


def comp_subgraph(name, p):
    print(name)
    f_orig=open(name, "r")
    f_fin=open(p+"/"+name, "w")
    lines=f_orig.readlines()
    l=8
    while l< len(lines):
        w=lines[l].replace("\n", "")
        w=w.replace("\t", " ")
        f_fin.write(w+" ")
        l+=1
        e=int(lines[l].replace("\n", ""))
        for j in range(1,e+1):
            w2=lines[l+j].replace("\n", "")
            w2=w2.replace("\t", " ")
            f_fin.write(w2+"\n")
            if e-j>=1:
                f_fin.write(w+" ")
        l=l+e+1
        if lines[l]=="0\n":
            f_fin.close()
            break
        

directory = './' #'the/directory/you/want/to/use'
if not os.path.exists(directory+"/new_graphs"):
    os.mkdir(directory+"/new_graphs")
else:
    for filename in os.listdir(directory):
        #print(filename)
        if filename.endswith(".txt") and "query_subgraph" in filename:
            comp_subgraph(filename, "new_graphs")

             
    





