#!/usr/bin/env python
# coding: utf-8


import os
import argparse
#copy and paste this file in the folder where the files generated by the C code are 
# for instance for the test_graph, copy the file where the files test_graph.txt_query_subgraph_0_1.txt, etc. are
# then just run it, it will generate a new folder and insert the correct file with the new format in the folder


#!/usr/bin/env python
# coding: utf-8
parser = argparse.ArgumentParser()

parser.add_argument("-d", "--dataset", type=str, default="default",help="The directory name of Relcomp generated output")
args = parser.parse_args()


def comp_subgraph(name, outname):
    print(name)
    f_orig=open(name, "r")
    f_fin=open(outname, "w")
    lines=f_orig.readlines()
    l=6
    if lines[l]=="0\n": 
        l+=2
    else:
        real_edge_num=int(lines[l])
        l+=1
        while l< len(lines):
            w=lines[l].replace("\n", "")
            w=w.replace("\t", " ")
            f_fin.write(w+" ")
            l+=1
            e=int(lines[l].replace("\n", ""))
            for j in range(1,e+1):
                w2=lines[l+j].replace("\n", "")
                w2=w2.replace("\t", " ")
                f_fin.write(w2+"\n")
                if e-j>=1:
                    f_fin.write(w+" ")
            real_edge_num-=1
            l=l+e+1
            if real_edge_num==0:
                l+=1 
                break   
    while l< len(lines):
        w=lines[l].replace("\n", "")
        w=w.replace("\t", " ")
        f_fin.write(w+" ")
        l+=1
        e=int(lines[l].replace("\n", ""))
        for j in range(1,e+1):
            w2=lines[l+j].replace("\n", "")
            w2=w2.replace("\t", " ")
            f_fin.write(w2+"\n")
            if e-j>=1:
                f_fin.write(w+" ")
        l=l+e+1
        if lines[l]=="0\n":
            f_fin.close()
            break
        
if __name__ == '__main__':
    directory = args.dataset 
    if not os.path.exists(directory+"_subg"):
        print('making new directory: ',directory+"_subg/")
        os.mkdir(directory+"_subg/")
    else:
        for filename in os.listdir(directory):
            if os.path.isfile(os.path.join(directory+"_subg/",filename)): # Skip outputs that are already generated
                continue 
            if filename.endswith(".txt") and "query_subgraph" in filename:
                print('generating subgraph from: ',filename, 'in directory: ',directory+"_subg/")
                comp_subgraph(os.path.join(directory,filename), os.path.join(directory+"_subg/",filename))

             
    







